### ISSUE TITLE
[Oriana Ampuero] proyecto 5

### ISSUE THREAD

**Issue by OrianAmpuero** [Ironhack-Data-Madrid-Mayo-2022/w5-Visualization-project#3]
https://github.com/OrianAmpuero/PROJECT4.git

**Comment by Gobuub** [comment]
Buen trabajo Oriana, quizás me ha faltado un poco más de storytelling en el readme, mas que explicar cuales son los datos que tenías, me refiero sobre todo a que valor puedes extraer de esos datos, que al final es lo que vas a tratar de explicar en el dashboard, pero esto solo a título informativo. Sigue así, que vas muy bien :).
