### ISSUE TITLE
[Irene Aguerri]

### ISSUE THREAD

**Issue by iaguerri** [Ironhack-Data-Madrid-Mayo-2022/w5-Visualization-project#5]
https://github.com/iaguerri/Elections_2019/

**Comment by iaguerri** [comment]
No está terminado, pero subo lo que tengo. Sorry

**Comment by Gobuub** [comment]
No hace falta que me pidas disculpas Irene, has currado y has llegado hasta donde has podido, pero you know, hay que ponerse las pilas.
